services:
  mysql-db:
    image: mysql
    container_name: hotel-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: inventory
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "5680:3306"
    networks:
      - mysql-app-network


volumes:
  db_data: {}
networks:
  mysql-app-network: